syntax enable
"colorscheme mustang
colorscheme desert
"colorscheme distinguished
set nohlsearch
set incsearch
set ignorecase
set number
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set smarttab

let g:airline_theme='onedark'
"let g:airline_theme='term'
"let g:airline_theme='wombat'
set laststatus=2
set belloff=all
